### ISSUE TITLE
how i can use this?

### ISSUE THREAD

**Issue by Gabiworld** [Yumacide/roblox-livestream#1]

**Comment by Yumacide** [comment]
Hello! It's been a while so this is probably irrelevant now, but you can compile this program by [installing Rust](https://rustup.rs) then running `cargo run --release` in a command line in the root directory of this repository.

Once it's running, it will respond to any requests on the port `127.0.0.1:7331` with a PNG image of your screen. You can then send requests to this port from a game running in Roblox Studio and decode the image using [this library](https://github.com/MaximumADHD/Roblox-PNG-Library) then create an EditableImage with it.

Note: I didn't really make this with other people in mind.
